exclude: 'build|stubs'

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [ '--branch=master' ]
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.254'
    hooks:
      - id: ruff
        args: [ '--fix', '--line-length', '100' ]
