path: /export/home/group03/dataset/aic19-track1-mtmc-train/train/train_yolov8/ # dataset root dir
train: images # relative to path
val: images # relative to path
test:  # test images (optional)

# Classes
names:
  0: car

