OUTPUT_DIR: "/ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s03_ByTrack"
DEBUG_RUN: false
FONTSIZE: 15
MOT:
  TRACKED_CLASSES: [2, 7] # ["cars", "truck"] [1, 2, 3, 5, 7]
  REID_MODEL_OPTS: "vehicle_models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "vehicle_models/resnet50_mixstyle/net_19.pth"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov8"
  TRACKER: "bytetrack_iou"
  MIN_FRAMES: 10
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "vehicle_models/color_svm.pkl"
    - type: "vehicle_models/type_svm.pkl"
  REFINE: false
  # VALID_ZONEPATHS: ["1,.*,2", "2,.*, 1", "3, .*,4", "4, .*, 3", "5, .*, 5"]
MTMC:
  CAMERA_LAYOUT: 'config/AI_city/s03_camera_layout.txt'
  LINKAGE: 'mean_feature'
  MIN_SIM: 0.5
EXPRESS:
  FINAL_VIDEO_OUTPUT: true
  CAMERAS:
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c011/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c011/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c011/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c012/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c012/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c012/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c013/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c013/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c013/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c014/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c014/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c014/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c015/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c015/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c015/calibration.txt"
EVAL:
  MIN_IOU: 0.34
  IGNORE_FP: true
  DROP_SINGLE_CAM: false
  GROUND_TRUTHS:
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c011/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c012/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c013/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c014/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c015/gt/gt.txt"
