OUTPUT_DIR: "output/experiment_debug"
FONTSIZE: 11
MOT:
  VIDEO: "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/vdo.avi"
  REID_MODEL_OPTS: "vehicle_models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "vehicle_models/resnet50_mixstyle/net_19.pth"
  CALIBRATION: "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/calibration.txt"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov8"
  TRACKER: "deepsort"
  DETECTION_MASK: "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/roi.jpg"
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "vehicle_models/color_svm.pkl"
    - type: "vehicle_models/type_svm.pkl"
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false