OUTPUT_DIR: "output/AI_city_s01_r"
DEBUG_RUN: false
FONTSIZE: 15
MOT:  
  TRACKED_CLASSES: [2, 7] # ["cars", "truck"] [1, 2, 3, 5, 7]
  REID_MODEL_OPTS: "vehicle_models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "vehicle_models/resnet50_mixstyle/net_19.pth"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov8"
  TRACKER: "deepsort"
  MIN_FRAMES: 10
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "vehicle_models/color_svm.pkl"
    - type: "vehicle_models/type_svm.pkl"
  REFINE: false
  # VALID_ZONEPATHS: ["1,.*,2", "2,.*, 1", "3, .*,4", "4, .*, 3", "5, .*, 5"]
MTMC:
  PICKLED_TRACKLETS: ['output/AI_city_s01/0_vdo/mot.pkl', 'output/AI_city_s01/1_vdo/mot.pkl', 'output/AI_city_s01/2_vdo/mot.pkl',
                        'output/AI_city_s01/3_vdo/mot.pkl', 'output/AI_city_s01/4_vdo/mot.pkl']
  CAMERA_LAYOUT: 'config/AI_city/s01_camera_layout.txt'
  LINKAGE: 'mean_feature'
  MIN_SIM: 0.5
EXPRESS:
  FINAL_VIDEO_OUTPUT: true
  CAMERAS:
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c002/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c002/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c002/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c003/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c003/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c003/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c004/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c004/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c004/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c005/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c005/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c005/calibration.txt"
EVAL:
  MIN_IOU: 0.34
  IGNORE_FP: true
  DROP_SINGLE_CAM: false
  GROUND_TRUTHS:
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c002/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c003/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c004/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c005/gt/gt.txt"
