OUTPUT_DIR: "output/cityflow_s01_c001"
FONTSIZE: 15
DEBUG_RUN: false
MOT:
  VIDEO: "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/vdo.avi"
  REID_MODEL_OPTS: "vehicle_models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "vehicle_models/resnet50_mixstyle/net_19.pth"
  # CALIBRATION: "datasets/cityflow_track3/train/S01/c001/calibration.txt"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov8"
  DETECTION_MASK: "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/roi.jpg"
  TRACKER: "deepsort"
  MIN_FRAMES: 5
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "vehicle_models/color_svm.pkl"
    - type: "vehicle_models/type_svm.pkl"
  ATTRIBUTE_INFER_BATCHSIZE: 1
  REFINE: false
EVAL:
  MIN_IOU: 0.34
  IGNORE_FP: true
  GROUND_TRUTHS:
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/gt/gt.txt"

