OUTPUT_DIR: "/ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou_OF/AI_city_s04_maxiou_OF"
MTMC:
  CAMERA_LAYOUT: 'config/AI_city/s04_camera_layout.txt'
  PICKLED_TRACKLETS:
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c016.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c017.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c018.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c019.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c020.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c021.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c022.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c023.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c024.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c025.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c026.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c027.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c028.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c029.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c030.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c031.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c032.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c033.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c034.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c035.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c036.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c037.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c038.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c039.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/mot_max_iou_OF/mot/S04/mot_features_c040.pkl"
  LINKAGE: 'mean_feature'
  MIN_SIM: 0.5
EVAL:
  MIN_IOU: 0.35
  IGNORE_FP: true
  DROP_SINGLE_CAM: true
  GROUND_TRUTHS:
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c016/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c017/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c018/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c019/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c020/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c021/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c022/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c023/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c024/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c025/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c026/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c027/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c028/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c029/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c030/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c031/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c032/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c033/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c034/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c035/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c036/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c037/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c038/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c039/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/mot_c040/gt/gt.txt'
