OUTPUT_DIR: "output/Ai_city_mtmc_eval"
MTMC:
  CAMERA_LAYOUT: 'config/AI_city/s01_camera_layout.txt'
  PICKLED_TRACKLETS:
    - "output/AI_city_s01/0_vdo/mot.pkl"
    - "output/AI_city_s01/1_vdo/mot.pkl"
    - "output/AI_city_s01/2_vdo/mot.pkl"
    - "output/AI_city_s01/3_vdo/mot.pkl"
    - "output/AI_city_s01/4_vdo/mot.pkl"
  LINKAGE: 'average'
  MIN_SIM: 0.5
EVAL:
  MIN_IOU: 0.35
  IGNORE_FP: true
  DROP_SINGLE_CAM: true
  GROUND_TRUTHS:
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c001/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c002/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c003/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c004/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S01/c005/gt/gt.txt"
