#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 1000 # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6
# commanda terminal --> sbatch --gres gpu:1 -n 10 job
python task_1_1.py --motion_type forward backward --block_size 4 8 16 32 64 --search_area 20 40 60 80 100 120 --step_size 8 16 32 64 --distance_type SAD SSD NCC 
#python task_1_1.py --motion_type forward backward --block_size 4 --search_area 20 40  --distance_type SAD  



