arcface: false
batchsize: 32
checkpoint: ''
circle: false
color_jitter: false
contrast: true
cosface: false
cosine: true
data_dir: ../datasets/
debug: false
debug_period: 100
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
grad_clip_max_norm: 50.0
ins_gamma: 32
instance: false
label_smoothing: 0.0
lifted: false
linear_num: 2048
lr: 0.02
mixstyle: true
model: resnet_ibn
model_subtype: default
name: resnet50_verzalcityvric_mixstyle
nclasses: 34071
num_workers: 3
samples_per_class: 4
save_freq: 1
sphere: false
start_epoch: 0
stride: 2
total_epoch: 20
tpu_cores: -1
train_csv_path: ../datasets/annot/train.csv
triplet: false
val_csv_path: ../datasets/annot/val.csv
warm_epoch: 2
