#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 1000 # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
# commanda terminal --> sbatch --gres gpu:1 -n 10 task_1_4
eval "$(conda shell.bash hook)"
conda activate m6
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy B_2
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy B_3
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy B_4
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy C_1
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy C_2
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy C_3
# python task1_3.py --task Task1_4 --network faster_RCNN --save_vis True --strategy C_4
# python task1_3.py --task Task1_3 --network mask_RCNN --save_vis True --strategy A
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy B_2
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy B_3
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy B_4
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy C_1
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy C_2
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy C_3
# python task1_3.py --task Task1_4 --network mask_RCNN --save_vis True --strategy C_4
python task1_3.py --task Task1_3 --network retinaNet --save_vis True --strategy A
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy B_2
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy B_3
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy B_4
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy C_1
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy C_2
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy C_3
python task1_3.py --task Task1_4 --network retinaNet --save_vis True --strategy C_4

