#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 1000 # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
# commanda terminal --> sbatch --gres gpu:1 -n 10 task_1_1
eval "$(conda shell.bash hook)"
conda activate m6
# python task1_1.py --network faster_RCNN --save_vis True
# python task1_1.py --network mask_RCNN --save_vis True
# python task1_1.py --network retinaNet --save_vis True
# python task1_1.py --network faster_RCNN_R50 --save_vis True
# python task1_1.py --network mask_RCNN_R50 --save_vis True
# python task1_1.py --network retinaNet_R50 --save_vis True
# python task1_1.py --network faster_RCNN_R101 --save_vis True
# python task1_1.py --network mask_RCNN_R101 --save_vis True
# python task1_1.py --network retinaNet_R101 --save_vis True

python json2txt.py --task Task_1_1 --network faster_RCNN --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/faster_RCNN/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network mask_RCNN --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/mask_RCNN/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network retinaNet --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/retinaNet/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network faster_RCNN_R50 --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/faster_RCNN_R50/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network mask_RCNN_R50 --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/mask_RCNN_R50/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network retinaNet_R50 --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/retinaNet_R50/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network faster_RCNN_R101 --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/faster_RCNN_R101/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network mask_RCNN_R101 --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/mask_RCNN_R101/coco_instances_results.json --strategy A
python json2txt.py --task Task_1_1 --network retinaNet_R101 --json_path /ghome/group03/mcv-m6-2023-team6/week3/Results/Task_1_1/retinaNet_R101/coco_instances_results.json --strategy A