#!/bin/bash
#SBATCH -n 10 # Number of cores
#SBATCH --mem 60GB # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6
# commanda terminal --> sbatch --gres gpu:1 -n 10 job 

# echo "Starting pre_MTMC.py"
# python pre_MTMC.py   # DONE

# python vehicle_mtmc/mtmc/run_mtmc.py --config AI_city/mtmc_s01_max_iou.yaml  # DONE
# python vehicle_mtmc/mtmc/run_mtmc.py --config AI_city/mtmc_s03_max_iou.yaml  # DONE
# python vehicle_mtmc/mtmc/run_mtmc.py --config AI_city/mtmc_s04_max_iou.yaml    # HA PETAT LINIA 81 ERROR    [2023-04-25 23:51:15,597]: Evaluation unsuccessful: probably EVAL config had some errors.


# echo "Starting mtmc/run_express_mtmc.py s03"
# python vehicle_mtmc/mtmc/run_express_mtmc.py --config AI_city/end2end_ByTrack_s03.yaml # Era un error de yaml, en teoria ha de funcionar

# echo "Starting mtmc/run_express_mtmc.py s03"
# python vehicle_mtmc/mtmc/run_express_mtmc.py --config AI_city/end2end_DeepSort_s03.yaml

# echo "Starting mtmc/run_express_mtmc.py s01"
# python vehicle_mtmc/mtmc/run_express_mtmc.py --config AI_city/end2end_DeepSort_s01.yaml

# echo "Starting mtmc/run_express_mtmc.py s01"
# python vehicle_mtmc/mtmc/run_express_mtmc.py --config AI_city/end2end_ByTrack_s01.yaml # DONE

# echo "Starting mtmc/run_express_mtmc.py s04"
# python vehicle_mtmc/mtmc/run_express_mtmc.py --config AI_city/end2end_ByTrack_s04.yaml  # Era un error de yaml, en teoria ha de funcionar

# echo "Starting mtmc/run_express_mtmc.py s04"
# python vehicle_mtmc/mtmc/run_express_mtmc.py --config AI_city/end2end_DeepSort_s04.yaml


echo "Starting MTSC.py for OF"
conda activate m6_clone
python MTSC.py --OF 1
python pre_MTMC.py --OF 1 

echo "Starting mtmc/run_express_mtmc.py s01"
conda activate m6
python vehicle_mtmc/mtmc/run_mtmc.py --config AI_city/mtmc_s03_max_iou_OF.yaml
python vehicle_mtmc/mtmc/run_mtmc.py --config AI_city/mtmc_s01_max_iou_OF.yaml
python vehicle_mtmc/mtmc/run_mtmc.py --config AI_city/mtmc_s04_max_iou_OF.yaml 

