#!/bin/bash
#SBATCH -n 10 # Number of cores
#SBATCH --mem 60GB # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6

echo "Starting TrackEval for EndToEnd MTSC"
echo "BY TRACK S01"
python TrackEval.py --seq S01 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s01_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC False --evaluated False 
python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
python TrackEval.py --seq S01 --endToEnd True --csv_name mtsc_byTrack_s01.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s01_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --evaluated True

#echo "BY TRACK S03"
#python TrackEval.py --seq S03 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s03_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC False --evaluated False 
#python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
#python TrackEval.py --seq S03 --endToEnd True --csv_name mtsc_byTrack_s03.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s03_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/data/trackers/mot_challenge/MOT17-train/MPNTrack/  --evaluated True

#echo "BY TRACK S04"
#python TrackEval.py --seq S04 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s04_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC False --evaluated False 
#python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
#python TrackEval.py --seq S04 --endToEnd True --csv_name mtsc_byTrack_s04.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s04_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/data/trackers/mot_challenge/MOT17-train/MPNTrack/  --evaluated True

#echo "BY DEEPSORT S01"


echo "Starting TrackEval for MTMC"
echo "MAX IOU S01"
python TrackEval.py --seq S01 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s01_maxiou/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC True --evaluated False 
python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
python TrackEval.py --seq S01 --endToEnd True --csv_name mtsc_MaxIoU_s01.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s01_maxiou/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --evaluated True

#echo "MAX IOU S03"
#python TrackEval.py --seq S03 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s03_maxiou/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC True --evaluated False 
#python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
#python TrackEval.py --seq S03 --endToEnd True --csv_name mtsc_MaxIoU_s03.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s03_maxiou/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/data/trackers/mot_challenge/MOT17-train/MPNTrack/  --evaluated True

#echo "MAX IOU S04"
#python TrackEval.py --seq S04 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s04_maxiou/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC True --evaluated False 
#python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
#python TrackEval.py --seq S04 --endToEnd True --csv_name mtsc_MaxIoU_s04.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s03_maxiou/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/data/trackers/mot_challenge/MOT17-train/MPNTrack/  --evaluated True



echo "BY TRACK S01"
python TrackEval.py --seq S01 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s01_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC True --evaluated False 
python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
python TrackEval.py --seq S01 --endToEnd True --csv_name mtmc_byTrack_s01.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s01_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S01/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --evaluated True

#echo "BY TRACK S03"
#python TrackEval.py --seq S03 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s03_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC True --evaluated False 
#python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
#python TrackEval.py --seq S03 --endToEnd True --csv_name mtmc_byTrack_s03.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s03_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/data/trackers/mot_challenge/MOT17-train/MPNTrack/  --evaluated True

#echo "BY TRACK S04"
#python TrackEval.py --seq S04 --endToEnd True --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s04_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/data/trackers/mot_challenge/MOT17-train/MPNTrack/ --MTMC True --evaluated False 
#python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
#python TrackEval.py --seq S04 --endToEnd True --csv_name mtmc_byTrack_s04.csv --input /ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_s04_ByTrack/ --output /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S04/data/trackers/mot_challenge/MOT17-train/MPNTrack/  --evaluated True
