#!/bin/bash
#SBATCH -n 10 # Number of cores
#SBATCH --mem 60GB # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6
# commanda terminal --> sbatch --gres gpu:1 -n 10 job_video



echo "Starting video max_iou"

conda activate m6
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou --seq S03 --cam c010 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/input/S03/c010.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou --seq S03 --cam c011 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/input/S03/c011.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou --seq S03 --cam c012 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/input/S03/c012.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou --seq S03 --cam c013 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/input/S03/c013.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou --seq S03 --cam c014 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/input/S03/c014.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou --seq S03 --cam c015 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/input/S03/c015.txt

echo "Starting video max_iou_OF"
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou_OF --seq S03 --cam c010 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou_OF/input/S03/c010.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou_OF --seq S03 --cam c011 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou_OF/input/S03/c011.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou_OF --seq S03 --cam c012 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou_OF/input/S03/c012.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou_OF --seq S03 --cam c013 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou_OF/input/S03/c013.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou_OF --seq S03 --cam c014 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou_OF/input/S03/c014.txt
python --output /ghome/group03/mcv-m6-2023-team6/week5/Results/videos/max_iou_OF --seq S03 --cam c015 --tracking /ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou_OF/input/S03/c015.txt

