#!/bin/bash
#SBATCH -n 10 # Number of cores
#SBATCH --mem 60GB # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6
# commanda terminal --> sbatch --gres gpu:1 -n 10 job_mtmc
cd /ghome/group03/mcv-m6-2023-team6/week5/vehicle_mtmc
export PYTHONPATH=$(pwd)
python mtmc/run_express_mtmc.py --config AI_city/express_s01.yaml